// p3_magi formulas (copied from tools/build_formulas.mjs; TeX list edited)
// Typeset every formula used in the film with MathJax (TeX -> self-contained SVG paths)
// and emit src/formulas.js so the renderer never depends on math fonts at runtime.
import { mathjax } from 'mathjax-full/js/mathjax.js';
import { TeX } from 'mathjax-full/js/input/tex.js';
import { SVG } from 'mathjax-full/js/output/svg.js';
import { liteAdaptor } from 'mathjax-full/js/adaptors/liteAdaptor.js';
import { RegisterHTMLHandler } from 'mathjax-full/js/handlers/html.js';
import { AllPackages } from 'mathjax-full/js/input/tex/AllPackages.js';
import fs from 'node:fs';

const F = {
  task: String.raw`c \equiv a + b \pmod{97}`,
  cosadd: String.raw`\cos\omega_k(a+b) = \cos\omega_k a\,\cos\omega_k b - \sin\omega_k a\,\sin\omega_k b`,
  omega: String.raw`\omega_k = \frac{2\pi k}{97}`,
  cosadd1: String.raw`\cos\omega_k(a+b) =`,
  cosadd2: String.raw`\cos\omega_k a\,\cos\omega_k b - \sin\omega_k a\,\sin\omega_k b`,
  adamw: String.raw`\theta \leftarrow \theta - \eta\Big(\frac{\hat m}{\sqrt{\hat v}+\epsilon} + \lambda\,\theta\Big)`,
  logits: String.raw`\mathrm{logits} = W_2\,\mathrm{ReLU}\big(W_1[E_a;E_b] + b_1\big) + b_2`,
  power: String.raw`P_k = \frac{\|\mathbf{c}_k^{\top}E\|^2 + \|\mathbf{s}_k^{\top}E\|^2}{\sum_j \big(\|\mathbf{c}_j^{\top}E\|^2 + \|\mathbf{s}_j^{\top}E\|^2\big)}`,
};



const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const tex = new TeX({ packages: AllPackages });
const svg = new SVG({ fontCache: 'none' });
const doc = mathjax.document('', { InputJax: tex, OutputJax: svg });

const out = {};
for (const [k, src] of Object.entries(F)) {
  const node = doc.convert(src, { display: true });
  let s = adaptor.innerHTML(node);                      // <svg ...>...</svg>
  const vb = s.match(/viewBox="([^"]+)"/)[1].split(/\s+/).map(Number);
  s = s.replace(/ width="[^"]+"/, '').replace(/ height="[^"]+"/, '').replace(/ style="[^"]*"/, '');
  s = s.replace('<svg ', `<svg width="${vb[2] / 10}" height="${vb[3] / 10}" `);
  out[k] = { svg: s, w: vb[2], h: vb[3] };
}
fs.writeFileSync(new URL('./formulas.js', import.meta.url),
  '// generated by opening_v2/p3_magi/build_formulas.mjs — do not edit\nwindow.FORMULAS = ' + JSON.stringify(out) + ';\n');
console.log('formulas:', Object.keys(out).length);
