"""
Build opening_v2/p3_magi/data.js from the real grokking run (opening_v2/shared/data/grokking.json).
Everything the film puts on screen is either copied from the log or derived here, deterministically.

    python3 opening_v2/p3_magi/build_data.py
"""
import json, math, os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
d = json.load(open(os.path.join(ROOT, 'opening_v2/shared/data/grokking.json')))
P = d['p']
steps = np.array(d['steps'], float)
va, vl, ta, tl, wn = (np.array(d[k], float) for k in ['val_acc', 'val_loss', 'train_acc', 'train_loss', 'wnorm'])


def crossing(y, thr, rising=True):
    """first logged interval where y crosses thr; linear interpolation in step."""
    for i in range(1, len(y)):
        a, b = y[i - 1], y[i]
        if (rising and a < thr <= b) or (not rising and a > thr >= b):
            return float(steps[i - 1] + (thr - a) / (b - a) * (steps[i] - steps[i - 1]))
    return None


LN_P = math.log(P)                               # loss of a uniform guess over 97 classes = 4.5747 nats
G0 = crossing(vl[steps > 1500], LN_P, rising=False)  # val loss falls back below chance level (after the memorization peak)
# crossing() uses the global steps array; recompute on the masked slice properly
m = steps > 1500
s_m, vl_m = steps[m], vl[m]
for i in range(1, len(vl_m)):
    if vl_m[i - 1] > LN_P >= vl_m[i]:
        G0 = float(s_m[i - 1] + (LN_P - vl_m[i - 1]) / (vl_m[i] - vl_m[i - 1]) * (s_m[i] - s_m[i - 1]))
        break
G50 = crossing(va, 0.5)
G99 = crossing(va, 0.99)
T100 = float(steps[np.argmax(ta >= 1.0)])        # first logged step with train acc == 1.0
i_pk = int(np.argmax(vl)); VPEAK = (float(steps[i_pk]), float(vl[i_pk]))
i_wpk = int(np.argmax(wn)); WPEAK = (float(steps[i_wpk]), float(wn[i_wpk]))

# the exact train/val split of grokking.py: rng = default_rng(0); perm = rng.permutation(P*P); first 30% train
rng = np.random.default_rng(0)
pairs = np.array([(a, b) for a in range(P) for b in range(P)])
perm = rng.permutation(len(pairs)); ntr = int(d['frac'] * len(pairs))
mask = np.zeros(P * P, np.uint8); mask[perm[:ntr]] = 1           # index = a*P + b
mask_hex = ''.join('%x' % int(''.join(str(x) for x in mask[i:i + 4].tolist() + [0] * (4 - len(mask[i:i + 4]))), 2) for i in range(0, P * P, 4))

F = np.array(d['fourier'])                         # [snap, 48] normalized power, k = 1..48
emb = np.array(d['emb2d'])                         # [snap, 97, 2]
snap = np.array(d['snap_steps'])
domk = (F.argmax(1) + 1).tolist()
r = np.linalg.norm(emb, axis=2); cv = (r.std(1) / r.mean(1)).round(4).tolist()
final = F[-1]; order = np.argsort(-final)
KEY = sorted(int(k + 1) for k in order[:7])        # 7 frequencies that carry >= 11% each at step 30k
key_share = F[:, [k - 1 for k in KEY]].sum(1).round(4).tolist()
top5_14k = [int(k + 1) for k in np.argsort(-F[list(snap).index(14000)])[:5]]

# measured throughput of grokking.py's own loop on this machine (time_steps.py, 1 thread, 400 steps incl. its eval/fourier logging; runs: 53.87, 54.07 ms)
MS_PER_STEP = float(os.environ.get('MS_PER_STEP', '0') or 0) or 53.97

out = dict(
    p=P, frac=d['frac'], lr=d['lr'], wd=d['wd'], ntrain=int(ntr), nval=int(P * P - ntr),
    steps=d['steps'], train_loss=d['train_loss'], val_loss=d['val_loss'], train_acc=d['train_acc'], val_acc=d['val_acc'], wnorm=d['wnorm'],
    snap=d['snap_steps'], fourier=d['fourier'], emb2d=d['emb2d'], domk=domk, cv=cv, key=KEY, key_share=key_share, top5_14k=top5_14k,
    G0=round(G0, 1), G50=round(G50, 1), G99=round(G99, 1), T100=T100, VPEAK=VPEAK, WPEAK=WPEAK, LN_P=LN_P,
    ms_per_step=MS_PER_STEP, mask=mask_hex,
)
with open(os.path.join(HERE, 'data.js'), 'w') as f:
    f.write('// generated by build_data.py from opening_v2/shared/data/grokking.json — do not edit\n')
    f.write('window.RUN = ' + json.dumps(out, separators=(',', ':')) + ';\n')
print(json.dumps({k: out[k] for k in ['ntrain', 'nval', 'G0', 'G50', 'G99', 'T100', 'VPEAK', 'WPEAK', 'key', 'top5_14k', 'ms_per_step']}))
print('final key share', key_share[-1], ' cv', cv[0], '->', cv[-1])
print('wallclock to G0 from 3000:', (G0 - 3000) * MS_PER_STEP / 1000, 's')
