// Typeset every formula used in the film with MathJax (TeX -> self-contained SVG paths)
// and emit src/formulas.js so the renderer never depends on math fonts at runtime.
import { mathjax } from 'mathjax-full/js/mathjax.js';
import { TeX } from 'mathjax-full/js/input/tex.js';
import { SVG } from 'mathjax-full/js/output/svg.js';
import { liteAdaptor } from 'mathjax-full/js/adaptors/liteAdaptor.js';
import { RegisterHTMLHandler } from 'mathjax-full/js/handlers/html.js';
import { AllPackages } from 'mathjax-full/js/input/tex/AllPackages.js';
import fs from 'node:fs';

const F = {
  energy: String.raw`E(\mathbf{x};f) = -T\,\log\sum_{i=1}^{K} e^{f_i(\mathbf{x})/T}`,
  msp: String.raw`\max_i\ \mathrm{softmax}\big(f(\mathbf{x}^{\ast})\big)_i = 0.973`,
  sync: String.raw`\mathrm{SYNC} \equiv \frac{\mathcal{L}^{\ast}}{\mathcal{L}_{\mathrm{train}}}`,
  syncNote: String.raw`\mathcal{L}^{\ast}\!:\ \text{irreducible (Bayes) loss}`,
  gap: String.raw`\Delta_{\mathrm{gen}} = \mathcal{L}_{\mathrm{val}} - \mathcal{L}_{\mathrm{train}}`,
  moe: String.raw`\mathbf{y} = \sum_{i \in \mathrm{Top}k(\mathbf{g})} g_i(\mathbf{x})\, E_i(\mathbf{x}),\quad \mathbf{g}(\mathbf{x}) = \mathrm{softmax}(W_r\mathbf{x})`,
  aux: String.raw`\mathcal{L}_{\mathrm{aux}} = \alpha N \sum_{i=1}^{N} f_i\, P_i`,
  rlhf: String.raw`\max_{\pi_\theta}\ \mathbb{E}_{y\sim\pi_\theta(\cdot\mid x)}\big[r_\phi(x,y)\big] \;-\; \beta\,\mathbb{D}_{\mathrm{KL}}\big[\pi_\theta(y\mid x)\,\big\|\,\pi_{\mathrm{ref}}(y\mid x)\big]`,
  gold: String.raw`R_{\mathrm{gold}}(d) = d\,(\alpha - \beta\log d),\quad d = \sqrt{\mathbb{D}_{\mathrm{KL}}(\pi\,\|\,\pi_{\mathrm{ref}})}`,
  san: String.raw`X^{(\ell+1)} = \mathrm{softmax}\!\Big(\tfrac{X W_Q (X W_K)^{\top}}{\sqrt{d_k}}\Big)\, X W_V`,
  bound: String.raw`\big\|\mathrm{res}(\mathrm{SAN}_L(X))\big\|_{1,\infty} \le \Big(\tfrac{4\gamma\beta}{\sqrt{d_{qk}}}\Big)^{\frac{3^L-1}{2}} \big\|\mathrm{res}(X)\big\|_{1,\infty}^{\,3^L}`,
  res: String.raw`\mathrm{res}(X) = X - \mathbf{1}\bar{\mathbf{x}}^{\top}`,
  skip: String.raw`X^{(\ell+1)} = X^{(\ell)} + \mathrm{SA}\big(X^{(\ell)}\big)`,
  atfield: String.raw`r_i^{\mathrm{AT}} = \big\|\mathbf{x}_i - \bar{\mathbf{x}}\big\|_2`,
  rank1: String.raw`\mathrm{rank}(X) \to 1`,
};

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const tex = new TeX({ packages: AllPackages });
const svg = new SVG({ fontCache: 'none' });
const doc = mathjax.document('', { InputJax: tex, OutputJax: svg });

const out = {};
for (const [k, src] of Object.entries(F)) {
  const node = doc.convert(src, { display: true });
  let s = adaptor.innerHTML(node);                      // <svg ...>...</svg>
  const vb = s.match(/viewBox="([^"]+)"/)[1].split(/\s+/).map(Number);
  s = s.replace(/ width="[^"]+"/, '').replace(/ height="[^"]+"/, '').replace(/ style="[^"]*"/, '');
  s = s.replace('<svg ', `<svg width="${vb[2] / 10}" height="${vb[3] / 10}" `);
  out[k] = { svg: s, w: vb[2], h: vb[3] };
}
fs.writeFileSync(new URL('../src/formulas.js', import.meta.url),
  '// generated by tools/build_formulas.mjs — do not edit\nwindow.FORMULAS = ' + JSON.stringify(out) + ';\n');
console.log('formulas:', Object.keys(out).length);
