// p2_mincho: typeset every formula of the film with MathJax (TeX -> SVG paths) into formulas.js.
//   node opening_v2/p2_mincho/build_formulas.mjs
import { mathjax } from 'mathjax-full/js/mathjax.js';
import { TeX } from 'mathjax-full/js/input/tex.js';
import { SVG } from 'mathjax-full/js/output/svg.js';
import { liteAdaptor } from 'mathjax-full/js/adaptors/liteAdaptor.js';
import { RegisterHTMLHandler } from 'mathjax-full/js/handlers/html.js';
import { AllPackages } from 'mathjax-full/js/input/tex/AllPackages.js';
import fs from 'node:fs';

const F = {
  // single glyphs used as "characters"
  theta: String.raw`\theta`,
  thetaStar: String.raw`\theta^{*}`,
  theta0: String.raw`\theta_{0}`,
  x: String.raw`x`,
  y: String.raw`y`,
  L: String.raw`\mathcal{L}`,
  partial: String.raw`\partial`,
  nabla: String.raw`\nabla`,
  empty: String.raw`\varnothing`,
  // the thesis, typeset
  attention: String.raw`\mathrm{Attention}(Q,K,V)=\mathrm{softmax}\!\left(\frac{QK^{\top}}{\sqrt{d_k}}\right)V`,
  attnL: String.raw`\mathrm{Attention}(Q,K,V)`,
  attnR: String.raw`=\mathrm{softmax}\!\left(\frac{QK^{\top}}{\sqrt{d_k}}\right)V`,
  softmax: String.raw`\mathrm{softmax}(\mathbf{z})_i=\frac{e^{z_i}}{\sum_{j} e^{z_j}}`,
  xent: String.raw`\mathcal{L}=-\sum_{i} y_i \log \hat{y}_i`,
  chain: String.raw`\frac{\partial \mathcal{L}}{\partial \theta}=\frac{\partial \mathcal{L}}{\partial \hat{y}}\,\frac{\partial \hat{y}}{\partial h}\,\frac{\partial h}{\partial \theta}`,
  dLdth: String.raw`\frac{\partial \mathcal{L}}{\partial \theta}`,
  sgd: String.raw`\theta\leftarrow\theta-\eta\,\nabla_{\theta}\mathcal{L}(\theta)`,
  argmin: String.raw`\theta^{*}=\operatorname*{arg\,min}_{\theta}\ \mathbb{E}_{(x,y)\sim\mathcal{D}}\big[-\log p_{\theta}(y\mid x)\big]`,
  heinit: String.raw`\sim\mathcal{N}\!\left(0,\,\frac{2}{n_{\mathrm{in}}}\right)`,
  block1: String.raw`\mathbf{x}\leftarrow\mathbf{x}+\mathrm{Attn}\big(\mathrm{LN}(\mathbf{x})\big)`,
  block2: String.raw`\mathbf{x}\leftarrow\mathbf{x}+\mathrm{MLP}\big(\mathrm{LN}(\mathbf{x})\big)`,
  block0: String.raw`\mathbf{x}=\mathrm{Embed}(\mathrm{tokens})`,
  block3: String.raw`\mathrm{logits}=W_U\,\mathrm{LN}(\mathbf{x})`,
  chinA: String.raw`L(N,D)=E+\frac{A}{N^{\alpha}}+\frac{B}{D^{\beta}}`,
  chinB: String.raw`E=1.69\quad A=406.4\quad B=410.7\quad \alpha=0.34\quad \beta=0.28`,
  resgrad: String.raw`\frac{\partial \mathcal{L}}{\partial \mathbf{x}_{\ell}}=\frac{\partial \mathcal{L}}{\partial \mathbf{x}_{L}}\left(1+\frac{\partial}{\partial \mathbf{x}_{\ell}}\sum_{i=\ell}^{L-1}\mathcal{F}(\mathbf{x}_{i})\right)`,
  resfwd: String.raw`\mathbf{x}_{L}=\mathbf{x}_{\ell}+\sum_{i=\ell}^{L-1}\mathcal{F}(\mathbf{x}_{i})`,
  one: String.raw`1`,
  lora: String.raw`W=W_{0}+BA`,
  relu: String.raw`\mathrm{ReLU}(x)=\max(0,x)`,
  fgsm: String.raw`\tilde{\mathbf{x}}=\mathbf{x}+\epsilon\,\mathrm{sign}\big(\nabla_{\mathbf{x}}\mathcal{L}(\theta,\mathbf{x},y)\big)`,
  ln10: String.raw`\mathcal{L}=-\log\tfrac{1}{10}=\ln 10\approx 2.303`,
  adam1: String.raw`m_t=\beta_1 m_{t-1}+(1-\beta_1)\,g_t`,
  adam2: String.raw`v_t=\beta_2 v_{t-1}+(1-\beta_2)\,g_t^{2}`,
  adam3: String.raw`\hat{m}_t=\frac{m_t}{1-\beta_1^{t}}`,
  adam4: String.raw`\hat{v}_t=\frac{v_t}{1-\beta_2^{t}}`,
  adam5: String.raw`\theta_t=\theta_{t-1}-\alpha\,\frac{\hat{m}_t}{\sqrt{\hat{v}_t}+\epsilon}`,
  gt: String.raw`g_t=\nabla_{\theta}\mathcal{L}(\theta_{t-1})`,
  beta2: String.raw`\beta_2`,
  beta1: String.raw`\beta_1`,
  eps: String.raw`\epsilon`,
  dmodel: String.raw`d_{\mathrm{model}}`,
  dff: String.raw`d_{\mathrm{ff}}`,
  dk: String.raw`d_k`,
  hh: String.raw`h`,
  NN: String.raw`N`,
  pdrop: String.raw`P_{\mathrm{drop}}`,
  els: String.raw`\epsilon_{ls}`,
  deltaTheta: String.raw`\Delta\theta`,
  clip: String.raw`\|g\|\le 1.0`,
};

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const tex = new TeX({ packages: AllPackages });
const svg = new SVG({ fontCache: 'none' });
const doc = mathjax.document('', { InputJax: tex, OutputJax: svg });

const out = {};
for (const [k, src] of Object.entries(F)) {
  const node = doc.convert(src, { display: true });
  let s = adaptor.innerHTML(node);
  const vb = s.match(/viewBox="([^"]+)"/)[1].split(/\s+/).map(Number);
  s = s.replace(/ width="[^"]+"/, '').replace(/ height="[^"]+"/, '').replace(/ style="[^"]*"/, '');
  s = s.replace('<svg ', `<svg width="${vb[2] / 10}" height="${vb[3] / 10}" `);
  // baseline: MathJax viewBox y0 is -(height above baseline)
  out[k] = { svg: s, w: vb[2], h: vb[3], asc: -vb[1] };
}
fs.writeFileSync(new URL('./formulas.js', import.meta.url),
  '// generated by build_formulas.mjs — do not edit\nwindow.FORMULAS = ' + JSON.stringify(out) + ';\n');
console.log('formulas:', Object.keys(out).length);
