import { chromium } from 'playwright';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const ROOT = '/home/user/Claude_workspace/projects/evangelion-deep-learning-video';
const srv = http.createServer((req, rsp) => { const p = path.join(ROOT, decodeURIComponent(new URL(req.url, 'http://x').pathname)); if (!fs.existsSync(p) || fs.statSync(p).isDirectory()) { rsp.writeHead(404); rsp.end(); return; } rsp.writeHead(200); fs.createReadStream(p).pipe(rsp); });
await new Promise(r => srv.listen(0, r));
const b = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--font-render-hinting=none'] }); const pg = await b.newPage({ viewport: { width: 1440, height: 1080 } });
await pg.goto(`http://127.0.0.1:${srv.address().port}/opening_v2/p2_mincho/index.html`);
await pg.evaluate(() => window.READY);
const url = await pg.evaluate(() => {
  window.renderFrame(Math.round(71.3 * 30)); const sc = document.getElementById('scene'); const sx = sc.getContext('2d');
  lat(sx, 'OUTLIERS 80', 20, 100, { size: 80, family: FGc, color: '#f80' });
  sx.font = '700 150px "Roboto Condensed"'; sx.fillStyle = '#f80'; sx.fillText('RAW 150', 20, 1000);
  return sc.toDataURL('image/png');
  const c = document.createElement('canvas'); c.width = 1440; c.height = 1080; const x = c.getContext('2d');
  x.fillStyle = '#000'; x.fillRect(0, 0, 1440, 1080);
  lat(x, 'OUTLIERS 80', 20, 100, { size: 80, family: FGc, color: '#fff' });
  lat(x, 'OUTLIERS 150', 20, 260, { size: 150, family: FGc, color: '#fff' });
  lat(x, 'OUTLIERS 300', 20, 560, { size: 300, family: FGc, color: '#fff' });
  x.font = '700 150px "Roboto Condensed"'; x.fillStyle = '#f80'; x.fillText('RAW 150', 20, 760);
  x.save(); x.scale(2, 2); x.font = '700 100px "Roboto Condensed"'; x.fillText('SCALED', 10, 470); x.restore();
  return c.toDataURL('image/png');
});
fs.writeFileSync(process.argv[2], Buffer.from(url.slice(22), 'base64'));
await b.close(); srv.close();
