import { chromium } from 'playwright';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const ROOT = '/home/user/Claude_workspace/projects/evangelion-deep-learning-video';
const srv = http.createServer((req, rsp) => { const p = path.join(ROOT, decodeURIComponent(new URL(req.url, 'http://x').pathname)); if (!fs.existsSync(p) || fs.statSync(p).isDirectory()) { rsp.writeHead(404); rsp.end(); return; } rsp.writeHead(200); fs.createReadStream(p).pipe(rsp); });
await new Promise(r => srv.listen(0, r));
const b = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--font-render-hinting=none'] }); const pg = await b.newPage({ viewport: { width: 1400, height: 900 } });
await pg.goto(`http://127.0.0.1:${srv.address().port}/opening_v2/p2_mincho/dev_fonttest.html`);
await pg.evaluate(() => window.READY);
await pg.screenshot({ path: process.argv[2] });
await b.close(); srv.close();
